local Vec3 = require "RayTracer.Math.Vec3"
local Ray = require "RayTracer.Math.Ray"
local Interval = require "RayTracer.Math.Interval"
local RNG = require "RayTracer.Math.RNG"
local Camera = require "RayTracer.Core.Camera"
local Scene = require "RayTracer.Core.Scene"
local Film = require "RayTracer.Core.Film"
local Renderer = require "RayTracer.Core.Renderer"
local NormalIntegrator = require "RayTracer.Integrator.NormalIntegrator"
local PathIntegrator = require "RayTracer.Integrator.PathIntegrator"
local RussianRoulette = require "RayTracer.Integrator.RussianRoulette"
local Sphere = require "RayTracer.Geometry.Sphere"
local Quad = require "RayTracer.Geometry.Quad"
local Triangle = require "RayTracer.Geometry.Triangle"
local AABB = require "RayTracer.Acceleration.AABB"
local BVH = require "RayTracer.Acceleration.BVH"
local Lambertian = require "RayTracer.Material.Lambertian"
local Metal = require "RayTracer.Material.Metal"
local Dielectric = require "RayTracer.Material.Dielectric"
local DiffuseLight = require "RayTracer.Material.DiffuseLight"
local SolidColor = require "RayTracer.Texture.SolidColor"
local Checker = require "RayTracer.Texture.Checker"
local ImageTexture = require "RayTracer.Texture.ImageTexture"
local PPMWriter = require "RayTracer.IO.PPMWriter"
local AsciiPresenter = require "RayTracer.IO.AsciiPresenter"
local AnsiPresenter = require "RayTracer.IO.AnsiPresenter"
local CallbackPresenter = require "RayTracer.IO.CallbackPresenter"

return {
    Vec3 = Vec3,
    Color = Vec3,
    Ray = Ray,
    Interval = Interval,
    RNG = RNG,
    Camera = Camera,
    Scene = Scene,
    Film = Film,
    Renderer = Renderer,
    NormalIntegrator = NormalIntegrator,
    PathIntegrator = PathIntegrator,
    RussianRoulette = RussianRoulette,
    Sphere = Sphere,
    Quad = Quad,
    Triangle = Triangle,
    AABB = AABB,
    BVH = BVH,
    Lambertian = Lambertian,
    Metal = Metal,
    Dielectric = Dielectric,
    DiffuseLight = DiffuseLight,
    SolidColor = SolidColor,
    Checker = Checker,
    ImageTexture = ImageTexture,
    PPMWriter = PPMWriter,
    AsciiPresenter = AsciiPresenter,
    AnsiPresenter = AnsiPresenter,
    CallbackPresenter = CallbackPresenter,
}
